#!/usr/bin/env python3
"""Generate the Wren pixel-art logo.

Source of truth for the logo: the GRID below is the hand-designed 16x16 pixel map.
Running this script regenerates wren.svg (scalable) and PNG rasters next to it.

    python3 assets/logo/generate_logo.py

Requires Pillow (pip install pillow).
"""
import json
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent  # repo root (assets/logo/ -> repo)

PALETTE = {
    '.': None,             # transparent
    'K': (42, 26, 16),     # outline dark brown
    'D': (95, 63, 34),     # dark brown  (back / wing / tail)
    'B': (160, 109, 59),   # body brown
    'L': (240, 215, 170),  # light buff belly
    'W': (251, 245, 233),  # brow highlight
    'E': (26, 18, 11),     # eye
    'Y': (235, 162, 60),   # beak
}

# 16 x 16. A wren facing right, tail cocked up-left.
GRID = [
    "................",
    "...KK...........",
    "..KDDK..........",
    "..KDDK...KKKKK..",
    "..KDDK..KBWWBK..",
    "..KDDK.KBBBBEBYY",
    "..KDDDKBBBBBBBY.",
    ".KDDBBBBBBBBBBK.",
    ".KDBDDBBBBBBBBK.",
    ".KDBDDBBBLLLLBK.",
    "..KDBBBBBLLLLBK.",
    "..KDBBBBLLLLLBK.",
    "...KBBBBLLLLBK..",
    "...KBBBBBBBBK...",
    "....KKK.KKK.....",
    ".....K...K......",
]

W = len(GRID[0])
H = len(GRID)
for i, row in enumerate(GRID):
    assert len(row) == W, f"row {i} len {len(row)} != {W}: {row!r}"


def _master():
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(GRID):
        for x, ch in enumerate(row):
            c = PALETTE[ch]
            if c:
                px[x, y] = (*c, 255)
    return img


def _ansi_art():
    """The wren as colored terminal art: two GRID rows per text line via the
    upper-half-block ``▀`` (fg = top pixel, bg = bottom pixel) with 24-bit ANSI.
    Transparent pixels fall back to the terminal's own background."""
    RESET = "\x1b[0m"
    lines = []
    for y in range(0, H, 2):
        top = GRID[y]
        bot = GRID[y + 1] if y + 1 < H else "." * W
        cells = ["   "]  # indent to sit under a 2-space banner
        for x in range(W):
            t = PALETTE[top[x]]
            b = PALETTE[bot[x]]
            if t is None and b is None:
                cells.append(RESET + " ")
            elif t is not None and b is None:
                cells.append(f"\x1b[49m\x1b[38;2;{t[0]};{t[1]};{t[2]}m▀")
            elif t is None and b is not None:
                cells.append(f"\x1b[49m\x1b[38;2;{b[0]};{b[1]};{b[2]}m▄")
            else:
                cells.append(
                    f"\x1b[48;2;{b[0]};{b[1]};{b[2]}m"
                    f"\x1b[38;2;{t[0]};{t[1]};{t[2]}m▀"
                )
        cells.append(RESET)
        lines.append("".join(cells))
    return "\n".join(lines)


def _plain_art():
    """Monochrome half-block fallback for NO_COLOR / non-truecolor terminals."""
    lines = []
    for y in range(0, H, 2):
        top = GRID[y]
        bot = GRID[y + 1] if y + 1 < H else "." * W
        row = ["   "]
        for x in range(W):
            t = top[x] != "."
            b = bot[x] != "."
            row.append("█" if t and b else "▀" if t else "▄" if b else " ")
        lines.append("".join(row))
    return "\n".join(lines)


def write_terminal_art():
    """Emit bin/wren-art.mjs — the shipped module the scaffolder imports.

    Lives in bin/ (not assets/) because .npmignore excludes assets/, so the
    published scaffolder must carry its art in the tarball."""
    content = (
        "// Wren terminal art — GENERATED by assets/logo/generate_logo.py.\n"
        "// Do not edit by hand; change the GRID in that file and regenerate.\n"
        f"export const wrenAnsi = {json.dumps(_ansi_art())};\n"
        f"export const wrenPlain = {json.dumps(_plain_art())};\n"
    )
    (ROOT / "bin" / "wren-art.mjs").write_text(content)


def write_social_card(master):
    """1280x640 GitHub social-preview card: the wren + a 'Wren' wordmark."""
    from PIL import ImageDraw, ImageFont

    CW, CH = 1280, 640
    bg = PALETTE['W']          # cream
    dark = PALETTE['K']        # dark brown wordmark
    body = PALETTE['D']        # body brown tagline

    def _font(size, bold=True):
        candidates = [
            "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold
            else "/System/Library/Fonts/Supplemental/Arial.ttf",
            "/System/Library/Fonts/Supplemental/Arial.ttf",
            "/System/Library/Fonts/Helvetica.ttc",
            "/Library/Fonts/Arial.ttf",
        ]
        for c in candidates:
            try:
                return ImageFont.truetype(c, size)
            except Exception:
                continue
        return ImageFont.load_default()

    img = Image.new("RGB", (CW, CH), bg)
    wren = master.resize((448, 448), Image.NEAREST)
    img.paste(wren, (150, (CH - 448) // 2), wren)  # alpha as its own mask
    draw = ImageDraw.Draw(img)

    tx = 640
    right_margin = 48
    avail = CW - tx - right_margin
    draw.text((tx, 205), "Wren", font=_font(180, True), fill=dark)

    # Auto-fit the tagline so it never clips the right edge.
    tagline = "An agentic research assistant for Claude Code"
    size = 40
    while size > 16:
        f = _font(size, False)
        if draw.textlength(tagline, font=f) <= avail:
            break
        size -= 2
    draw.text((tx + 4, 440), tagline, font=_font(size, False), fill=body)
    img.save(HERE / "wren-social.png")


def main():
    master = _master()

    # PNG rasters (nearest-neighbour keeps the pixels crisp)
    for size in (512, 128, 64, 32):
        name = "wren.png" if size == 512 else f"wren-{size}.png"
        master.resize((size, size), Image.NEAREST).save(HERE / name)

    # SVG (one rect per pixel; crisp at any scale)
    rects = []
    for y, row in enumerate(GRID):
        for x, ch in enumerate(row):
            c = PALETTE[ch]
            if c:
                rects.append(f'<rect x="{x}" y="{y}" width="1" height="1" fill="rgb{c}"/>')
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'shape-rendering="crispEdges" width="256" height="256">\n'
        + "\n".join(rects) + "\n</svg>\n"
    )
    (HERE / "wren.svg").write_text(svg)

    # Derived brand assets (same GRID/PALETTE, so they never drift):
    write_terminal_art()          # bin/wren-art.mjs (scaffolder banner)
    write_social_card(master)     # assets/logo/wren-social.png (GitHub card)

    print("wrote wren.svg, wren.png (512), wren-128.png, wren-64.png, wren-32.png, "
          "wren-social.png, and bin/wren-art.mjs")


if __name__ == "__main__":
    main()
