#!/usr/bin/env python3
"""Generate scheduled-job runners + registration files from research-config.yml.

For each ENABLED job under the config's `scheduler:` block, this writes a runner
shell script (with paths resolved for this machine) plus a launchd plist (macOS)
or a crontab line (Linux). It does NOT register the job for you — it prints the
exact command to activate it, so nothing touches your system without your say-so.

Run via:  ./setup.sh --with-schedule   (or)   python3 scripts/setup/install_scheduled.py

Notes:
- Scheduled headless runs need the EXACT MCP tool name in --allowedTools, or that
  step is silently skipped. The digest job includes the Gmail draft tool only when
  integrations.gmail.enabled is true.
- launchd/cron start with a minimal PATH; the runner sets PATH to include the
  detected `claude` and common bin dirs so node/npm/claude resolve.
"""
from __future__ import annotations  # keep `X | None` annotations lazy for Python 3.9

import os
import shutil
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_templates import load_config, dig  # noqa: E402  (same-dir import)

ROOT = Path(__file__).resolve().parent.parent.parent
SCHED_DIR = ROOT / "scripts" / "scheduled"
LOG_REL = "outputs/_logs"
CRON_DOW = {"Sun": 0, "Mon": 1, "Tue": 2, "Wed": 3, "Thu": 4, "Fri": 5, "Sat": 6}


def jobs_registry(cfg: dict) -> dict:
    """Config-key -> how to run it. Keep --allowedTools explicit and exact."""
    gmail = bool(dig(cfg, "integrations", "gmail", "enabled"))
    digest_tools = "WebSearch WebFetch Read Write Edit Bash"
    if gmail:
        digest_tools += " mcp__claude_ai_Gmail__create_draft"
    return {
        "weekly_digest": {
            "desc": "Weekly literature digest (/lit-digest)",
            "command": (
                '"$CLAUDE_BIN" -p "/lit-digest" --model sonnet '
                '--permission-mode acceptEdits '
                f'--allowedTools "{digest_tools}"'
            ),
            "cadence": "weekly",  # uses day + at
        },
        "nightly_memory": {
            "desc": "Nightly corpus-memory audit (npm run memory:audit)",
            "command": "npm run memory:audit",
            "cadence": "daily",  # uses at
        },
    }


def parse_hhmm(s: str):
    h, m = str(s or "09:00").split(":")
    return int(h), int(m)


def runner_text(key: str, job: dict, claude_bin: str) -> str:
    bindir = os.path.dirname(claude_bin) or "/usr/local/bin"
    return f"""#!/usr/bin/env bash
# {key} — {job['desc']}
# GENERATED by scripts/setup/install_scheduled.py — re-run to regenerate.
set -uo pipefail
PROJECT_ROOT="{ROOT}"
CLAUDE_BIN="{claude_bin}"
export PATH="{bindir}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
cd "$PROJECT_ROOT" || exit 1
mkdir -p "$PROJECT_ROOT/{LOG_REL}"
LOG_FILE="$PROJECT_ROOT/{LOG_REL}/{key}_$(date +%Y-%m-%d).log"
if [ -f "$PROJECT_ROOT/scripts/utils/notify.sh" ]; then
  source "$PROJECT_ROOT/scripts/utils/notify.sh"
else
  notify() {{ :; }}
fi
notify START "{key}" "scheduled run"
if {job['command']} >> "$LOG_FILE" 2>&1; then
  notify DONE "{key}" "see $LOG_FILE"
  exit 0
else
  rc=$?
  notify ERROR "{key}" "exit $rc — see $LOG_FILE"
  exit $rc
fi
"""


def plist_text(label: str, runner: Path, hh: int, mm: int, dow: int | None) -> str:
    cal = ""
    if dow is not None:
        cal += f"    <key>Weekday</key><integer>{dow}</integer>\n"
    cal += f"    <key>Hour</key><integer>{hh}</integer>\n"
    cal += f"    <key>Minute</key><integer>{mm}</integer>\n"
    logdir = ROOT / LOG_REL
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>{label}</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>{runner}</string></array>
  <key>StartCalendarInterval</key>
  <dict>
{cal}  </dict>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>{logdir}/{label}.out.log</string>
  <key>StandardErrorPath</key><string>{logdir}/{label}.err.log</string>
</dict>
</plist>
"""


def main() -> None:
    cfg = load_config()
    platform = (dig(cfg, "scheduler", "platform") or "none").lower()
    namespace = dig(cfg, "project", "namespace") or "wren"
    claude_bin = shutil.which("claude") or "claude"
    registry = jobs_registry(cfg)

    SCHED_DIR.mkdir(parents=True, exist_ok=True)
    (ROOT / LOG_REL).mkdir(parents=True, exist_ok=True)

    enabled = [
        (k, v) for k, v in registry.items()
        if dig(cfg, "scheduler", "jobs", k, "enabled")
    ]
    if not enabled:
        print("No scheduled jobs enabled in research-config.yml (scheduler.jobs.*.enabled).")
        print("Enable one, then re-run:  ./setup.sh --with-schedule")
        return

    cron_lines = []
    launchd_steps = []
    for key, job in enabled:
        hh, mm = parse_hhmm(dig(cfg, "scheduler", "jobs", key, "at") or "09:00")
        day = dig(cfg, "scheduler", "jobs", key, "day")
        dow = CRON_DOW.get(day) if (job["cadence"] == "weekly" and day) else None

        runner = SCHED_DIR / f"{key}.sh"
        runner.write_text(runner_text(key, job, claude_bin))
        runner.chmod(runner.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        print(f"  ✓ wrote {runner.relative_to(ROOT)}  ({job['desc']})")

        if platform == "launchd":
            label = f"com.{namespace}.{key.replace('_', '-')}"
            plist = SCHED_DIR / f"{label}.plist"
            plist.write_text(plist_text(label, runner, hh, mm, dow))
            print(f"  ✓ wrote {plist.relative_to(ROOT)}")
            launchd_steps.append(
                f"cp {plist} ~/Library/LaunchAgents/ && "
                f"launchctl load ~/Library/LaunchAgents/{plist.name}"
            )
        elif platform == "cron":
            dow_field = str(dow) if dow is not None else "*"
            cron_lines.append(f"{mm} {hh} * * {dow_field} /bin/bash {runner}  # {namespace}:{key}")

    print()
    if platform == "launchd":
        print("To activate (macOS launchd) — run each, then check `launchctl list | grep %s`:" % namespace)
        for s in launchd_steps:
            print(f"  {s}")
        print("\nTest a job now without waiting:  bash scripts/scheduled/<job>.sh")
    elif platform == "cron":
        print("To activate (Linux cron) — add these lines with `crontab -e`:")
        for c in cron_lines:
            print(f"  {c}")
        print("\nTest a job now without waiting:  bash scripts/scheduled/<job>.sh")
    else:
        print(f"scheduler.platform is '{platform}' — runners generated but not registered.")
        print("Set platform to 'launchd' (macOS) or 'cron' (Linux) and re-run to get activation steps.")


if __name__ == "__main__":
    main()
